# Generated by Django 5.0.6 on 2024-08-04 21:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='This is the product', max_length=3067, null=True),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='reason',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=tinymce.models.HTMLField(max_length=3067),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='My vending shop', max_length=3067, null=True),
        ),
        migrations.AlterField(
            model_name='vendorreview',
            name='review_text',
            field=tinymce.models.HTMLField(max_length=3067),
        ),
    ]
