# Generated by Django 5.0.6 on 2024-08-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(default='My product', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_title',
            field=models.CharField(default='BLUST BY DR MA', max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('subcategory_title', 'category')},
        ),
    ]
